-- ============================================================
-- MIGRATION: Add user-level isolation and new admin features
-- ============================================================

-- 1. Add user_id to orders
ALTER TABLE orders ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- 2. Add user_id to supplier_inquiries
ALTER TABLE supplier_inquiries ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE supplier_inquiries ADD COLUMN IF NOT EXISTS user_email TEXT;
ALTER TABLE supplier_inquiries ADD COLUMN IF NOT EXISTS user_name TEXT;
ALTER TABLE supplier_inquiries ADD COLUMN IF NOT EXISTS admin_notes TEXT;
ALTER TABLE supplier_inquiries ADD COLUMN IF NOT EXISTS supplier_ref TEXT;
ALTER TABLE supplier_inquiries ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;

-- 3. Favorites table (per user)
CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL,
  product_data JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);

-- 4. Cart items table (per user)
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL,
  qty INTEGER NOT NULL DEFAULT 1,
  product_data JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);

-- 5. Notifications table (per user)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL DEFAULT 'info',
  title TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  data JSONB DEFAULT '{}',
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Discount messages table
CREATE TABLE IF NOT EXISTS discount_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  user_email TEXT NOT NULL,
  user_name TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_reply TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
);

-- ============================================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================================

-- Orders RLS
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS orders_select_policy ON orders;
CREATE POLICY orders_select_policy ON orders
  FOR SELECT USING (
    auth.uid() = user_id OR
    auth.email() = 'rehanilyas20196@gmail.com'
  );
DROP POLICY IF EXISTS orders_insert_policy ON orders;
CREATE POLICY orders_insert_policy ON orders
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Favorites RLS
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS favorites_select_policy ON favorites;
CREATE POLICY favorites_select_policy ON favorites
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS favorites_insert_policy ON favorites;
CREATE POLICY favorites_insert_policy ON favorites
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS favorites_delete_policy ON favorites;
CREATE POLICY favorites_delete_policy ON favorites
  FOR DELETE USING (auth.uid() = user_id);

-- Cart Items RLS
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cart_items_select_policy ON cart_items;
CREATE POLICY cart_items_select_policy ON cart_items
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS cart_items_insert_policy ON cart_items;
CREATE POLICY cart_items_insert_policy ON cart_items
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS cart_items_update_policy ON cart_items;
CREATE POLICY cart_items_update_policy ON cart_items
  FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS cart_items_delete_policy ON cart_items;
CREATE POLICY cart_items_delete_policy ON cart_items
  FOR DELETE USING (auth.uid() = user_id);

-- Notifications RLS
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS notifications_select_policy ON notifications;
CREATE POLICY notifications_select_policy ON notifications
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS notifications_insert_policy ON notifications;
CREATE POLICY notifications_insert_policy ON notifications
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS notifications_update_policy ON notifications;
CREATE POLICY notifications_update_policy ON notifications
  FOR UPDATE USING (auth.uid() = user_id);

-- Discount Messages RLS (admin only for select, anyone can insert)
ALTER TABLE discount_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS discount_messages_select_policy ON discount_messages;
CREATE POLICY discount_messages_select_policy ON discount_messages
  FOR SELECT USING (
    auth.uid() = user_id OR
    auth.email() = 'rehanilyas20196@gmail.com'
  );
DROP POLICY IF EXISTS discount_messages_insert_policy ON discount_messages;
CREATE POLICY discount_messages_insert_policy ON discount_messages
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS discount_messages_update_policy ON discount_messages;
CREATE POLICY discount_messages_update_policy ON discount_messages
  FOR UPDATE USING (auth.email() = 'rehanilyas20196@gmail.com');

-- Supplier Inquiries RLS
ALTER TABLE supplier_inquiries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS supplier_inquiries_select_policy ON supplier_inquiries;
CREATE POLICY supplier_inquiries_select_policy ON supplier_inquiries
  FOR SELECT USING (
    auth.uid() = user_id OR
    auth.email() = 'rehanilyas20196@gmail.com'
  );
DROP POLICY IF EXISTS supplier_inquiries_insert_policy ON supplier_inquiries;
CREATE POLICY supplier_inquiries_insert_policy ON supplier_inquiries
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS supplier_inquiries_update_policy ON supplier_inquiries;
CREATE POLICY supplier_inquiries_update_policy ON supplier_inquiries
  FOR UPDATE USING (auth.email() = 'rehanilyas20196@gmail.com');

-- ============================================================
-- INDEXES for performance
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_user_id ON cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_discount_messages_status ON discount_messages(status);
CREATE INDEX IF NOT EXISTS idx_supplier_inquiries_user_id ON supplier_inquiries(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
