-- Products table schema
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(12,2) NOT NULL,
  category TEXT,
  image_url TEXT,
  rating DECIMAL(3,2) DEFAULT 0,
  reviews_count INTEGER DEFAULT 0,
  stock INTEGER DEFAULT 0,
  condition TEXT DEFAULT 'New'
);

-- Recommended items table schema
CREATE TABLE IF NOT EXISTS recommended_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  desc TEXT NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  image TEXT,
  category TEXT
);

-- Orders table schema
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  full_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  province TEXT NOT NULL,
  city TEXT NOT NULL,
  area TEXT NOT NULL,
  building_street TEXT NOT NULL,
  colony_suburb TEXT NOT NULL,
  address TEXT NOT NULL,
  label TEXT, -- 'OFFICE' or 'HOME'
  total_amount DECIMAL(12,2) NOT NULL,
  status TEXT DEFAULT 'pending',
  payment_method TEXT,
  payment_screenshot TEXT,
  items JSONB -- To store cart item details
);

-- Deals table schema
CREATE TABLE IF NOT EXISTS deals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  discount TEXT NOT NULL,
  image TEXT NOT NULL,
  category TEXT
);

-- Supplier inquiries table schema
CREATE TABLE IF NOT EXISTS supplier_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  item_name TEXT NOT NULL,
  details TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit TEXT NOT NULL DEFAULT 'Pcs',
  status TEXT NOT NULL DEFAULT 'pending'
);
